//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.09 at 09:33:25 PM PST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.mitchell.com/examples/claim", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tyler.mitchell.MitchellClaims.model;
